import Image from 'next/image'
import styles from './page.module.css'
import Topbar from './Component/topbar';
import Header from './Component/header';
import { Fragment } from 'react';

export default function Home() {
  return (
    <Fragment>
      <Topbar/>
      <div className={styles.centerDiv}>
        <div className={styles.holderParent}>
          <Header text="Critical Reflection"/>
          <div className={styles.textHolder}>
            <p>The purpose of any writing class is to help new writers, like me, to write more effectively. For me, I found the class quite effective because it overall changes the way I think about the writing process. As I progress through the paper, I will be demonstrating a few of the critical skills that show that I’ve improved, as a writer.</p>
            <p>The first skillset I want to demonstrate is the Writing process, for this one, we, as a student, should be able to describe and reflect on the writing that supports our goal. For my first major assignment, I was conflicted with two different topics that I wanted to choose: “The right to repair” and “stop paid textbooks”. At the time, I already had a strong background for my first choice of the topic, and for me to improve as a writer, I needed to be able to write for a new topic that I’ve never seen before, which is how a writer improves. This topic was also important for me, because as a student myself, I was able to not only relate to the topic, but also be affected by it as well. Another reason for my choice of topic is because of the types of audience that I’ll be facing. If I were to choose the first option (rights to repair), I would have a much broader audience. In an argument, the more specific the audience is, the more effective your writing will be, which for the second option, I was able to do. For my second assignment, the purpose is to Rhetorically reflect on the first assignment; this includes looking at the first assignment’s exigence, audience, rhetor, and constraint. Throughout the papers, I had several ideas of what each section would be about, but ultimately I made my choice after considering the overall effectiveness that it brings when using each of the choices. For the third assignment, we’re supposed to create a video media that represents one of our literacy. For this one, I’ve selected “technological literacy” mostly because that represented who I am throughout my lifetime, making it an effective choice for this assignment. For our fourth assignment, our goal is to write a literary analysis, targeting students. One of the largest constraints is the audience, since I have to assume that they do not understand any of the topics. I was able to workaround this constraint by heavily defining and quoting from a few of the popular literary authors. By adding quotes rather than just my own words, it increases my ethos or the reputation of my writing.</p>
            <p>The next critical skill I’ve demonstrated is the ability to create content that involves multiple literacies. It’s important to know that I use this writing skill in conjunction with the reading assignments because it allows me to understand what the different multi-literacy is and how it affects the outcome of the writing, specially, the reading for Brant allowed me to understand the concept of literacy sponsors and power, while Brant allowed me to have deeper understanding of what literacy and discourse is and relationship with identity. So for my third reading assignment I was able to incorporate several literacy and multimedia. I was able to use a simple animation software to create a compelling visual effect for my audience and used captions to incorporate a first-person narrative for my literacy story. In order for me to create the animation, I also need to have basic literacy skills for the software itself. For my fourth assignment, I was able to demonstrate such skills by discussing the different literacy stills involved in the video. Some of them include analyzing my parent’s literacies and identity, as well as how her powers and ideology shaped my literacy and ideology. I also discussed multiple sponsors that were involved and how they shaped my literacy skills as well.</p>
            <p>The next skill I’ll be discussing is variation across context. This one demonstrates our ability to analyze content rhetorically from multiple perspectives or contexts. I was able to demonstrate this in assignment two by incorporating several analyses that depended on many external contexts. In my writing, I was able to analyze and explain some of the techniques I’ve used in order to maximize the effectiveness of the argument, while being presented with several constraints. For example, the argument I was analyzing was created in the form of a blog. Knowing that, in order to make an effective blog, I’ve added images to it. I also attempted to use more academic vocabulary, knowing that my target audience is a professor. And unlike my fourth argument, this paper didn’t include any definition and quoting because the target audience for that assignment is my writing professor; thus, it is unnecessary to include it since they already have the knowledge to understand the writing.</p>
            <p>Another skill I’ll be demonstrating is decision making. Throughout all of my writing assignments, there will be a lot of writing choices I made based on the constraint I’m presented with. For the first and second assignment, one of the biggest constraints is myself. The inability to write a good paper really puts pressure on me. So one of the ways I was able to reduce the pressure is to write a small paragraph and take a break to brainstorm my next step of writing. Eventually, I’ll be able to come up with a decent idea. There’s also an issue with who my audience is going to be, not only a more specific audience, but which specific audience I want to choose. My initial thought was that either a politician or school administration. The reason behind politicians is so that they can make policy that applies to all the schools, but that didn’t work out well because it requires either a large population to complain or bribe them with a large sum of money. School administration also didn’t work well, since it’s also hard to convince them to block something that earns them commission. After reading feedback from different people, I went with professors, mostly because they have direct control over textbooks. The style of the writing is also different between those two assignments because the first assignment was written in a blog format, directed towards multiple professors, while the second assignment is written in an essay, directed forward by my English professor. Now for the third and fourth assignment, this assignment was both slightly more difficult and easier. For the third assignment, specifically, it was a bit more difficult because It’s really my first time doing a video as an assignment, so it’s hard to come up with ways to make one initially. After looking around, I was able to find Powtoon, a video making platform to make a simple animation video. Now the fourth assignment is slightly easier since the target audiences are students. What makes this paper different from others is now we have to include citations and quotes. Because of that, I have to brainstorm some ways I can smoothly incorporate quotes with the content I want to write. I also formatted the paper so that each definition has its own paragraph, since it’s something I’ve come up with initially.</p>
            <p>Writing and Power is also another critical skill since it forces students to examine the relationship between identity, literacy, language, and power. This was especially shown in my fourth assignment where we’re required to analyze the relationship from the third assignment. For example, in the paper, I was able to identify that my parents and teachers ideology led to the purchase of the hardware which resulted in me learning more about the tech. This shows the relationship that certain ideology can lead to literacy. Since both my teachers and parents are adults, they have more power to purchase things for me, which is the relationship that powers can enable literacy. I was also able to show that both ideology and power can restrict one's literacy skill by demonstrating that my parent’s anti-video game belief and their power as a parent prevented me from gaining much video literacy. The readings are also critical to my skills because they provide context to how I use the term.</p>
            <p>Lastly, revision is also another skill that’s important for writers because the ability to take feedback and improve your writing can drastically improve your reader’s experience. Attending office hours was also one of my best decisions I’ve made since it allows the professor, who has more experience, to provide more insight feedback. For the first assignment, I’ve improved small formatting such as left-sided text rather than center to make them more readable. For the second assignment, using the teacher’s conference, I was able to increase the details of my analysis paper, making it much stronger. There’s also feedback about re-writing certain sections of my analysis, but I wasn’t able to do that at the time because I find it difficult to implement with my current writing skills. For the third assignment,I was able to modify the audio track to fit the scene better. Lastly, for the fourth assignment, I’ve accepted small changes, such as adding the reading’s context to the paper so that the reader can have a better understanding of where the terms are coming from. Though there are many excellent feedbacks that were rejected due to time constraints. For example, I was suggested to group each term to a sponsor instead of creating each paragraph for it (i.e. when discussing my parents, instead of mentioning them in each paragraph, I should discuss it all in one place instead). But because of how I wrote my paper, it would require a full rewrite, which isn’t enough time before it’s due, so I had to drop it.</p>
            <p>Overall, there are still several spots where I can improve myself as a writer, such as writing a full-detailed analysis, but this class has certainly taught me to think differently when writing any type of paper and to consider the restrictions you’ll be facing while still being able to write an effective paper.</p>
          </div>
        </div>
      </div>
    </Fragment>
  )
}
